### ISSUE TITLE
feature request: ability to scope down the request waiting

### ISSUE THREAD

**Issue by idxn** [rasjani/robotframework-seleniumtestability#5]
**Background:** sometimes in our staging we face a problem with 3rd party components (analytics and digital marketing to track the event) from time to time so it would be great if we can have this kind of the ability to scope down the request waiting for just the url we are interested (our system under test of course)

**Comment by rasjani** [comment]
I do agree that this is a good feature and can be implemented.. But.

Im using https://github.com/alfonso-presa/testability-browser-bindings to catch most the events and i just recently moved to use directly it as upstream so that i don't have to maintain it.  I'll check if it would be possible to incorporate this sort of feature into it - it shouldnt be too hard and probably can even suply a patches to upstream.. 

I also do have another approach that could provide this sort of functionality - one could provide alternative "testability" javascript implementation that just follows the same js api to seleniumtestability and then users could be provide their own bindings and/or additional features to what is already provided. 

PS. Really good feature request and gives me confidence that things actually work. Thanks!

**Comment by rasjani** [comment]
https://github.com/alfonso-presa/testability-browser-bindings/issues/1

**Comment by rasjani** [comment]
This might be the "final" feature for 1.0.0 release.. I now have proof of concept patch https://github.com/rasjani/testability-browser-bindings/tree/blacklist

**Comment by rasjani** [comment]
blacklist changes merged into upstream - dunno if there will be "official" release into npm soon or not or should i just package testability-browser-bindings straight from the git..

**Comment by idxn** [comment]
Thanks @rasjani for this great work

**Comment by idxn** [comment]
@rasjani will we have a release for this?

**Comment by rasjani** [comment]
@idxn yes, feature wise, i think things look good for 1.0.0 release but maybe some for of rc before ..  this week anyway
