### ISSUE TITLE
Testability automatic wait is enabled after test case fails

### ISSUE THREAD

**Issue by Pakkanen1** [rasjani/robotframework-seleniumtestability#54]
So I have a problem where testability automatic wait is somehow enabled after a test fails. I've used **Disabled Testability Automatic Wait** in the suite setup to disable it during the suite execution. When a test fails inside the suite, it moves on to the next test (as robot should) and the first selenium keyword that is executed fails with this error: **TimeoutException: Message: Timed out waiting for testability ready callback to trigger.** This is problematic as a single failed test will fail all of the tests that come after it in the testsuite.

As a test I put a call for **Disabled Testability Automatic Wait** as the first step in the test case that causes this TimeoutException, and **the test passed.** This leads me to believe that the automatic wait is somehow enabled after test failure. 

## Expected Behavior
Testability automatic wait should not be enabled at runtime automatically. If testability automatic wait is disabled in the setup, it should stay disable during the suite.

## Actual Behavior
Testability automatic wait is enabled after any test case fails.

## Steps to Reproduce the Problem

  1. Create suite with more than 1 test case
  2. Import seleniumlibrary with the testability plugin
  3. Create suite setup that disables testability automatic wait
  4. Make it so that the first test case fails. (fe. wait for element that is not present)
  5. Run the suite

## Specifications

  - SeleniumTestability version: 1.1.0
  - Operating System: WIN10-Pro 64bit
  - Browser Version: Chrome 85.0.4183.102
  - WebDriver Version: ChromeDriver 85.0.4183.83

## Log URL
[SeleniumTestability.log](https://gist.githubusercontent.com/Pakkanen1/d84d285a83d9ca16c0653b2fdd2a5804/raw/945d9dc2e0ab2172980e678e033c0bd31756027d/SeleniumTestability.log)

I have also enclosed the failing keyword stacktrace from the html.log file: [HtmlLog](https://gist.githubusercontent.com/Pakkanen1/44df4875437cce8c79d31171519aa20a/raw/1c43989fe5414e0b8149816da78d968e7cca122d/HtmllogTRACEseleniumtestability1)

**Comment by rasjani** [comment]
Looking into this

**Comment by rasjani** [comment]
Ok, first sorry this took  a time but i've gone thru your logs (Btw, SUPERB bug report!) and it looks like this:

Initial initialization happens like this:

```
2020-09-11 09:23:52,218 - SeleniumTestability - DEBUG - __init__(<SeleniumLibrary.SeleniumLibrary object at 0x03BC6DF0>,False,60 Seconds,False,False)
2020-09-11 09:23:52,378 - SeleniumTestability - DEBUG - disable_testability_automatic_wait(, ) [ENTERING]
2020-09-11 09:23:52,378 - SeleniumTestability - DEBUG - set_testability_automatic_wait(False, ) [ENTERING]
2020-09-11 09:23:52,378 - SeleniumTestability - DEBUG - set_testability_automatic_wait() [LEAVING]
2020-09-11 09:23:52,378 - SeleniumTestability - DEBUG - disable_testability_automatic_wait() [LEAVING]
2020-09-11 09:23:55,581 - TestabilityListener - DEBUG -  **** New Session Created for TestabilityListener  **** 
```

which means that you where loading testability plugin and setting automatic wait and injection off by default and then also calling disable automatic wait - not really required but better make it sure.

But after this, the log shows following:

```
2020-09-11 09:25:14,119 - SeleniumTestability - DEBUG - __init__(<SeleniumLibrary.SeleniumLibrary object at 0x03BC6DF0>,True,30 seconds,True,True)
```

This essentially mean that seleniumlibrary initializes itself because the library is loaded again with different settings (and this time with automatic wait and injecting set to be on). There would be ways to workaround this but its rather hard and most likely cannot be made 100% to cover all the corner cases.

How to fix this or make it work for you really depends on your test/suite structure. 

Let me know a bit more if this doesn't help ?

**Comment by Pakkanen1** [comment]
I have a dozen suites that use a common resource file where SL+SeleniumTestability is imported. Is it not possible for the library to initialize itself with the initial values used in the test run?

**Comment by rasjani** [comment]
Thats up to SeleniumLibrary (and to certain degree, Robot framework's implementation) to decide because of how SeleniumTestability (at the moment) lifetime is handled by SeleniumLibrary. 

I could have a separate global context, that, when initialized would be then checked on re-inits from SeleniumTestability but, that would be really complicated because user might still want to override the situation on test case and suite basis and options could be mixed with at library  keyword level (constructor) and explicit keywords during test itself or test setup/teardown ..  For this, i'd need a extra listener that monitors from where the calls are being made  and track the state based on what rf listener is providing.. 

I do have one question thought, you said that you set automatic waiting at suite level.  Does that in your case mean that you have one "robot" file with single suite setup and within that you have a test case failure but next testcase within that single "robot" file fails because automatic waiting was set back to true ?  Cuz that should definitely *not* happen ... 

Anyway, the answer to your question:  If you have single resource file that does something that looks something like this:

```robotframework
*** Settings ***
Library         SeleniumLibrary  plugins=SeleniumTestability;False;30 seconds;False
```

and you have multiple robot files (aka suites) that include that exact resourcefile, the initialization is shared between all of them (and most likely won't even be re-initialized but previous instance) will be used .. However, from the seleniumtestability.log's perspective, you had second call:

```
*** Settings ***
Library         SeleniumLibrary  plugins=SeleniumTestability;True;29 seconds;True,
```

*OR* Just:
```robotframework 
*** Settings ***
Library         SeleniumLibrary  plugins=SeleniumTestability
```
because essentially all the parameters in the second initialization where default ones indicating that maybe they where not provided..

**Comment by rasjani** [comment]
Now, with crude hack, it would be possible that when ever default values would be passed at plugin initialization, i could cache the previous values and re-use them if no new ones are provided but that would still leave a corner case of how to distinquish between:

```
Library         SeleniumLibrary  plugins=SeleniumTestability
## And
Library         SeleniumLibrary  plugins=SeleniumTestability;True;30 seconds;True;True
```

maybe setting the default values to `None` and override them at runtime to what the defaults are, if any of the keyword arguments where to be set, store all 4 into somewhere and then fetch then during init.. 

But this will once again cause issues with people  running things in parallel with tools like pabot.

**Comment by Pakkanen1** [comment]
So I looked for what could re-initialize testability and I found the problem. I had registered a custom keyword to be run on failure, which had a call to a custom python keyword, that prints browser console log using testability.
```
def get_library_instance() -> SeleniumLibrary:
    selib = BuiltIn().get_library_instance('SeleniumLibrary')
    return selib

def print_browser_console_log():
    selib = get_library_instance()
    print(plugin.SeleniumTestability(ctx=selib).get_log())
```
I tested it out and with the call to this keyword commented out, testability is no longer re-initialized after failed tests. I remember doing this to only generate a single row in the log, but thought that it would use the configuration from the current instance. (Such as "get_library_instance" in seleniumlibrary)

I switched to a pure robot version, which seems to cause no problems. Thank you for debugging this!
